### ISSUE TITLE
Delete Architecture & Overview Guide once 0.3.0 is published

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/docs#165]
in https://github.com/kabanero-io/docs/pull/143 we moved the guide to the docs since it makes more sense there.

We need to delete the guide repo (or rename it with a leading `draft-`) so it doesn't get published as a guide anymore. It will be under the Overview tab in the docs section instead.

**Comment by SueChaplain** [comment]
@alohr51 

Will it look odd that we don't have anything in the Kabanero Basics - Let's get started area?
Perhaps we should leave it there until we have other general guides to contribute.

@bschrammIBM ? I thought it was perfectly fine as a guide (meets your criteria), but since it is being moved, do we have anything else to fill the hole?

**Comment by jantley-ibm** [comment]
@alohr do you need a separate issue to delete the heading and empty section if there are no guides for it? (per @SueChaplain 's comment above)

**Comment by alohr51** [comment]
@jantley-ibm no, the section would just not appear if there are no docs for it

**Comment by jantley-ibm** [comment]
@alohr perfect, thanks!

**Comment by marikaj123** [comment]
@jantley-ibm or @alohr51 - Is there any pending work that needs to be done or is it ready to be closed?

**Comment by alohr51** [comment]
I just renamed it and archived the repo https://github.com/kabanero-io/draft-guide-overview so it doesn't show as a guide anymore.
