### ISSUE TITLE
Create blog post re: what's new in 0.5.0

### ISSUE THREAD

**Issue by jantley-ibm** [kabanero-io/docs#262]

**Comment by nateziemann** [comment]
I’d be happy to review and help with final messaging, but someone else needs to take the pen on the release blogs

**Comment by jantley-ibm** [comment]
Here's my very rough first draft of the what's new blog post for Kabanero 0.5.  I'm not sure everything is accurate, but it's a start.

-----------------------------

What's New in Release 0.5.0
Today we proudly present the next release of Kabanero, version 0.5.0. Check out the changes we have for you.

Tekton Triggers

Tekton Triggers are now supported in Kabanero eventing.  Kabanero pipelines now include one TriggerTemplate and two TriggerBindings (for github-push and github-pull-request events) per pipeline.  Due to this change, if you have existing webhooks that you created in a previous version of Kabanero, you will need to delete them and recreate them.  ((seems like this section needs one more sentence after the first one))

Kabanero Console adds Github OAuth option

The Kabanero Console can now be configured to user GitHub OAuth authorization.  This allows a user to log in with their GitHub ID and manage their collections through the Kabanero Console UI.  Right now, a user can only view their collections and their current status, but there is more to come with this feature in upcoming releases.

Appsody Operator updated to version 0.3.0

We've adopted a newer version of the Appsody Operator, which added support for basic service binding and for init containers array.  ((I couldn't find a good statement of what the value prop was for version 0.3))

In addition, we now allow multiple stack versions to be active simultaneously, we've added the the ability to use multiple collection repositories, and we've made improvements to collection lifecycles.  We hope you enjoy this new release!

**Comment by nateziemann** [comment]
What's New in Release 0.5.0
Today we proudly present the next release of Kabanero, version 0.5.0. Check out the changes we have for you.

**Github OAuth integration**

From  the console you can now configure user GitHub OAuth authorization. This allows a user to log in with their GitHub ID and manage their collections through the Kabanero Console UI. Until now, a user can only view their collections and their current status.  There is more to come with this feature in upcoming releases so stay tuned.

**Tekton Triggers**

The pipelines provided by Kabanero now leverage Tekton Triggers to _<value statement>_.   This includes one TriggerTemplate and two TriggerBindings (for github-push and github-pull-request events) per pipeline. _<what does this enable that couldn't be done in the past>._  Due to this change, if you have existing webhooks created in a previous version, you will need to delete them and recreate them. _<What's the bigger story we want to tell here as a future outlook>_

**Moved to new version 0.3.0 of Appsody open source project**

We've moved up to a newer version of the Appsody, including the developer CLI and the Deployment Operator for Application Stacks used  by our pre-built pipelines.   Many new features are included in Appsody 0.3.0, for  more details _<link or summarize here, get Neeraj and David to help.  I know they added  more detailed operational metadata container labeling, if they have basic service binding I'm surprised but we should discuss how to message that ...>_

**Additional honorable mentions in the release:**

- Multiple Application Stack versions can now be active simultaneously.  <value statement, this one should be a compelling limitation we're lifting>
- Ability to use multiple collection repositories**  <value statement>
- Code hygiene and bug fixes.

We hope you enjoy this new release!

**Comment by nateziemann** [comment]
@stephenkinder please add  some of your technical mumbo jumbo above.

**Comment by kaczyns** [comment]
I don't think we're declaring support for activating multiple versions of a collection in this release..... the operator knows how to do it, but the CLI and landing page don't know how to show the user that they've done it.

**Comment by nateziemann** [comment]
@ralanlittle @stevenschader please read above draft and help review for technical accuracy and help make it better.  I took a stab at enhancing what Jeff Antley started but in my humble opinion we still need some work to polish this.

**Comment by stephenkinder** [comment]
Tekton trigger support in Kabanero enables execution of pipelines and tasks based on specific Github events. The lifecycle of microservice development is reflected by the developers interaction with Git.  Git pull, merge, tag, pull requests all reflect well-known points in that microservice's lifecycle.  Tekton triggers allows for fine-grained optimized tasks to be assigned to respond to those lifecycle events. 

The multi-version support in the operator is an enablement layer and its full value won't  be realized until 0.6.0.

**Comment by alohr51** [comment]
@jantley-ibm @nateziemann Steve provided some more context, are we going to include a 0.5.0 blog or should we just do a small blurb on the pop up modal on the website (with no link to a blog)?

**Comment by mingcyu** [comment]
Jeff to work with Andrew today on moving this forward

**Comment by alohr51** [comment]
@jantley-ibm do you know if there is there a second rough draft ready for approval with Steve's comments added?

**Comment by jantley-ibm** [comment]
@alohr I contacted Neeraj and David about the Appsody line but have not gotten a response yet.  Let's go with this if you're ready to publish:

**What's New in Release 0.5.0**

Today we proudly present the next release of Kabanero, version 0.5.0. Check out the changes we have for you.

**Github OAuth integration**

From the console you can now configure user GitHub OAuth authorization. This allows a user to log in with their GitHub ID and manage their collections through the Kabanero Console UI. Until now, a user can only view their collections and their current status. There is more to come with this feature in upcoming releases so stay tuned.

**Tekton Triggers**

The pipelines provided by Kabanero now leverage Tekton triggers.   Tekton trigger support in Kabanero enables execution of pipelines and tasks based on specific Github events. The lifecycle of microservice development is reflected by the developers interaction with Git. Git push, merge, tag, pull requests all reflect well-known points in that microservice's lifecycle. Tekton triggers allows for fine-grained optimized tasks to be assigned to respond to those lifecycle events.  Due to this change, if you have existing webhooks created in a previous version, you will need to delete them and recreate them.

In addition to these changes, there are also code hygiene and bug fixes.

We hope you enjoy this new release!

**Comment by anneqm** [comment]
Hi!  @jantley-ibm @stephenkinder Just saw this... The sentence, "Tekton triggers allows for fine-grained optimized tasks to be assigned to respond to those lifecycle events."  This capability of triggers described in that sentence is not leveraged in Kab 0.5.0.  I suggest either it be changed to a future statement or removed altogether.

**Comment by kabanerogithub** [comment]
@anneqm is this sentence still true after that line is deleted? 
>Due to this change, if you have existing webhooks created in a previous version, you will need to delete them and recreate them.

**Comment by alohr51** [comment]
@anneqm is this sentence still true after the one you mentioned is deleted?

>Due to this change, if you have existing webhooks created in a previous version, you will need to delete them and recreate them.

**Comment by anneqm** [comment]
Yes!   that's the main reason we need to have statements around the addition of Triggers. That's the most important sentence!
