### ISSUE TITLE
Documentation for stack images needs to be updated

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/docs#416]
In Kabanero versions prior to 0.9.0, all the stack images used to be in the project kabanero in docker hub. This has changed recently as Open Liberty and Quarkus stacks use appsody project.
stack: docker.io/appsody/java-openliberty:0.2

    All the existing projects for OpenLiberty will have Kabanero which will need to be replaced with appsody
    2.Use of appsody instead of kabanero for some stacks will cause confusion. So we need to recommend users to always find out what / to use in appsody-config.yaml file from stack hub yaml file.

### Add label "documentation-id"
- Add the `documentation-id` bug label to this issue.

### What version of Kabanero does this apply to?
- Latest __
  or
- Specify versions: _____

### Specify what you want documented (required):
Complete the following information:

#### To create a topic:
- Specify a link to the section in the navigation where the topic should go:
- Specify a first draft of the topic that you want added:

#### To update existing topics:
- Specify links to the topics that are affected:
- Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:

**Comment by SueChaplain** [comment]
@jantley-ibm has updated the OL stack guide to refresh the system output, which shows the image being pulled from docker.io/appsody instead of Kabanero. However, adding a note to this guide to explain the change does not make any sense to me. The guide is to help users get started with developing a microservice from an OL stack, and we are likely to add confusion here by referring to where the stack used to come from. 

I'm assuming we will be mentioning the (tech. preview) Quarkus stack in the What's New for 0.9.0.So why don't we mention in there that the Quarkus and OL application stacks are now sourced from the Appsody project directly? 

@mtamboli - does that work for you?
@scottkurz ?

**Comment by jantley-ibm** [comment]
Removed the note from the guide and added to the what's new for 0.9 blog. Closing.
