### ISSUE TITLE
More guidance needed in the README for contributors

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#52]
The README suggests creating directories under /ref/ that correspond to the category of document you are writing ....... if there isn't one that's suitable, create one.

@bschrammIBM - do you have a view on what categories should be created, based on your doc plan? 

E.g.

- installation
- guides
- ref

It might be better to start with a structure that writers can contribute to, rather than people creating their own without a good understanding of the overall doc content?

@alohr51 - I also think we need some guidance on front matter. All docs currently written are in the /ref/general directory and have the following front matter:

:page-layout: general-reference
:page-type: general
:page-title: Kabanero Collections
:linkattrs:

Presumably this front matter is used to organise the doc on the website? How would this front matter change based on the location of the doc under /ref please? Might be worth adding a few notes to the README.

**Comment by alohr51** [comment]
@SueChaplain There will be a `doc-category` front matter variable that we will use for the categories so the docs go under the right header.

We have an issue https://github.com/kabanero-io/kabanero-website/issues/73 that is related to this categorization that is almost done which will include a README update. @bschrammIBM will get us the categories when she has them. Barbara said the doc work will be going through some more design so that's why the categories aren't ready.

**Comment by bschrammIBM** [comment]
This cannot be decided until the "installation-specific" design is finalized.

**Comment by bschrammIBM** [comment]
Hi - based on the discussion today, we won't have any doc categories or subdirectories. We will have Guides and Reference. Each guide will be in a unique repo. The current reference content will be the Management CLI. So the contributing.md should discuss how to create and submit a Guide. Doubtful that users will submit reference text.
