### ISSUE TITLE
Write a guide to describe "Working with Collections"

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#55]
Post MVP - we need a guide for "Working with Collections"

**Comment by SueChaplain** [comment]
This was written up by @groeges (Thanks!), which I think might be very useful for this issue when someone starts it. (Best viewed as a markdown file ... just rename it to .md extension)


[collection-structure.txt](https://github.com/kabanero-io/docs/files/3596470/collection-structure.txt)

**Comment by marikaj123** [comment]
@SueChaplain  - Is the issue ready for the label ID-reviewed?

**Comment by SueChaplain** [comment]
@marikaj123 - no, not ready. The input shown in this issue is simply something I knew existed and added it to the issue to help. The developer assigned to this issue (https://github.com/kvijai82) is, I believe, a developer in the Tekton team who has not provided anything so far ... possibly because it might be better assigned to a developer in the Collections team. Can you confirm who you expect to work on this from the developer end and I'll get in touch. I was assuming it might be someone in @ianpartridge team.

**Comment by marikaj123** [comment]
@tseelbach and @ianpartridge- would this be under pipeline or collection?

**Comment by kilnerm** [comment]
@SueChaplain The Collections README should be a good starting point... https://github.com/kabanero-io/collections/blob/master/README.md.

Could you have a look and let me know if anything else is needed?

**Comment by SueChaplain** [comment]
Initial draft repo created and populated with a very early draft. More work needed.
https://github.com/kabanero-io/draft-guide-working-with-collections

**Comment by marikaj123** [comment]
@SueChaplain - Please let us know in case of any help is needed.

**Comment by SueChaplain** [comment]
I've posted my latest updates to the draft guide repo: https://github.com/kabanero-io/draft-guide-working-with-collections but I need some help from development if this is ready to go for Friday.

The content is largely drawn from information provided by @groeges - thanks Steve! The final piece I tried to add is to have the user modify a collection as part of this guide and then test that the changes worked. The collections developers are not necessarily expert in the details of the stacks, so this was guess work on my part and something is not correct.

First I tried to change the version of OpenLiberty in the `incubator/java-microprofile/image/project/pom.xml` file from 19.0.0.8 to 19.0.0.9, but Maven didn't like it. So then I tried to change the http port from 9080 to 9090, hoping to see the starter app on localhost:9090 ... but the build spits out a container port that cannot be browsed. I guess I don't understand things well enough to get any further.

```
[Container] [INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://928f7aa9deee:9090/
```

Who can help please? 

FYI @kilnerm @marikaj123 

@stephenkinder @mtamboli ... please also confirm if this content is largely what you were expecting from your side.

**Comment by stephenkinder** [comment]
@SueChaplain this is excellent and it is indeed what I was looking for.  We've been using the term "_Kabanero Collection Hub_" to describe the set of collections that are built as part of this process -- is that something we want to reinforce in this article?   If we can connect this guide to using it, _e.g._ Now that you've built your customized collection hub, remember to 1) publish the release URL to your developers -- so they can setup Appsody/Codewind to point at the new collection hub, and 2) activate the collections in the target Kabanero instance so that the Tekton pipelines can be installed in that environment; with perhaps links to articles at how to do such things.

**Comment by SueChaplain** [comment]
@stephenkinder - thanks for the feedback, very useful. I have included that at the end of the guide. +1

**Comment by SueChaplain** [comment]
Andrew has kindly staged these at: https://kabanero-ajlohr.us-south.cf.test.appdomain.cloud/guides/
