### ISSUE TITLE
Todd: doc to specify Kab CLI service metadata in kabanero operator yaml

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#66]
See: https://github.com/kabanero-io/kabanero-operator/wiki/Todd's-input-for-the-Kabanero-operator

**Comment by bschrammIBM** [comment]
@davco01a Is there an update to the docs required for this? The referring issues says : `This needs to be reevaluated after discussion with the originating requestor` and is in Closed status. Can this issue also be closed?

**Comment by davco01a** [comment]
@bschrammIBM Yes, we will need doc, I am in the process of writing up doc at this wiki right now:

https://github.com/kabanero-io/kabanero-operator/wiki/Todd's-input-for-the-Kabanero-operator

**Comment by bschrammIBM** [comment]
Should this be in a readme? Is it part of installation and configuration?

**Comment by davco01a** [comment]
@bschrammIBM recommends we add a step to:

https://kabanero.io/docs/#scripted-kabanero-foundation-setup.html

to configure the Kabanero document

**Comment by davco01a** [comment]
* Specify repository URL in the Kabanero document (object) to point to cloned, customized index.yaml for the master collection
* In `kabanero crd` specify:
  - git `group or organization` in the `organization` field
  - git `team name(s)` in the `teams` field
  - the `api github url` in the `apiurl` field.
  - the kabanero `namespace(s)` in the `namespaces` field
  

 @tim.kaczynski is this only one single CRD for the Kab operator to get updated?

**Comment by kaczyns** [comment]
@davco01a You modify the CR instance of the Kabanero CRD.  So if the user created one Kabanero instance then that's the one that they'd modified.  Today, we only support one instance, in the Kabanero namespace, so that's the one they'd modify.  And most of the fields you're referring to there are not merged yet (see PR https://github.com/kabanero-io/kabanero-operator/pull/170)

**Comment by davco01a** [comment]
Ok, I want to to net out which fields Todd needs to focus on for modification and document those.

**Comment by jantley-ibm** [comment]
@davco01a @kaczyns @bschrammIBM Looks like the best place for this is https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc -- could you recommend where the new content would go in the workflow on that page?

**Comment by davco01a** [comment]
I thought @kaczyns gave recommendations on reordering the content of this page and placing the Kab document updates accordingly, but I don't see those changes reflected yet

**Comment by kaczyns** [comment]
We had been working thru this page:
https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc

One way we could slice this... is to insert steps between step 1 and 2.  Basically:
1a) Create the initial tagged release of the cloned collections (v1)
1b) Create any org-level teams that should administer the cloned collection and add members to those teams.
1c) Alter the Kabanero document to point to that named release (v1) and add the Github: section pointing to the github org, team(s), and api url

then continue on.... but when we get to step 7 we have to figure out what to do because you can't test the changes until you've pushed them back to your remote (cloned) github repository

I think move 7 to after 9.  So 7 would be push back, 8 would be make a release (not final version), and 9 would be test by altering the Kabanero document to point to the release.  if errors are found iterate back and update the release.  Then 10 would be to declare the release final.
I think that just editing step 1 addresses this issue.

**Comment by jantley-ibm** [comment]
There is a pull request with the discussed changes waiting for review:
https://github.com/kabanero-io/docs/pull/91

**Comment by davco01a** [comment]
Wel @jantley-ibm added some comments to your PR

**Comment by marikaj123** [comment]
@jantley-ibm - Does the issue contain what is needed for the ID team to provide the 'ID-reviewed' label?

**Comment by davco01a** [comment]
At this point in time we are really working off of:

https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc

**Comment by davco01a** [comment]
I also have this issue open to retitle this document:

https://github.com/kabanero-io/docs/issues/119

**Comment by davco01a** [comment]
Additionally:

Bullet one of Step 3 needs some rework - 

Specify the repository URL in the Kabanero document (object) to point to a cloned, customized index.yaml for the master collection. The URL setting is in the Spec.Collections.Repositories section of the Kabanero Custom Resource (CR) instance. You can either alter the Kabanero CR instance that already exists, or delete it and create a new one.

**Comment by davco01a** [comment]
Also some mention of step 3 about how to edit the Kabanero document would be help, e.g. oc edit or how to navigate to the CR from within the OKD console

@mtamboli ^^

**Comment by marikaj123** [comment]
@mtamboli - From SVT perspective, do you have what you need? 
@davco01a and @kaczyns - Since ID work @jantley-ibm is complete, is the issue ready to close?

**Comment by kaczyns** [comment]
@davco01a I think your comments are addressed in PR #127 .  Could you please review that?

**Comment by jantley-ibm** [comment]
@SueChaplain these docs are currently being revised by @kaczyns per https://github.com/kabanero-io/docs/pull/127/files.  If the guide covers all of the proposed updates then I'll recommend removing the reference topics.

**Comment by davco01a** [comment]
Once https://github.com/kabanero-io/docs/pull/127 is merged, then we can close this

**Comment by kaczyns** [comment]
#127 is merged, I am closing this issue.  #134 was opened to make an edit to the new page.
